export const INSTITUTIONS = [
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "Obafemi Awolowo University (OAU)",
  "University of Nigeria, Nsukka (UNN)",
  "Ahmadu Bello University (ABU)",
  "University of Benin (UNIBEN)",
  "Covenant University",
  "Lagos State University (LASU)",
  "Federal University of Technology, Akure (FUTA)",
  "University of Ilorin (UNILORIN)",
  "McPherson University",
  "Babcock University",
  "Landmark University",
  "Pan-Atlantic University",
  "American University of Nigeria (AUN)",
  "Nile University of Nigeria",
  "Baze University",
  "Bowen University",
  "Lead City University",
  "Redeemer's University",
  "Afe Babalola University (ABUAD)",
  "Mountain Top University",
  "Anchor University",
  "Augustine University",
  "Chrisland University",
  "Hallmark University",
  "Bells University of Technology",
  "Joseph Ayo Babalola University (JABU)",
  "Veritas University",
  "Gregory University, Uturu",
  "Igbinedion University, Okada",
  "Madonna University",
  "Ajayi Crowther University",
  "Al-Hikmah University",
  "Salem University",
  "Bingham University",
  "Caritas University",
  "Kwararafa University",
  "Novena University",
  "Renaissance University",
  "Rhema University",
  "Southwestern University",
  "Wellspring University",
  "Wesley University",
  "Western Delta University",
  "Caleb University",
  "Fountain University",
  "Oduduwa University",
  "Paul University",
  "Skyline University Nigeria",
  "Dominican University Ibadan",
  "Koladaisi University",
  "Legacy University, Okija",
  "Spiritan University, Nneochi",
  "Precious Cornerstone University",
  "PAMO University of Medical Sciences",
  "Atiba University Oyo",
  "Eko University of Medicine and Health Sciences",
  "Greenfield University",
  "Dominion University",
  "Trinity University",
  "Westland University",
  "Topfaith University",
  "Thomas Adewumi University",
  "Maranatha University",
  "Ave Maria University",
  "Al-Ansar University",
  "Margaret Lawrence University",
  "Khalifa Isyaku Rabiu University",
  "Sports University, Idumuje-Ugboko",
  "Baba Ahmed University",
  "Saisa University of Medical Sciences and Technology",
  "Mudiame University",
  "Havilla University",
  "Claretian University of Nigeria",
  "Karl-Kumm University",
  "Nok University",
  "James Hope University",
  "Maryam Abacha American University of Nigeria",
  "Capital City University",
  "Ahman Pategi University",
  "University of Offa",
  "Mewar International University",
  "Edusoko University",
  "Philomath University",
  "Khadija University",
  "Anan University",
  "Clifford University",
  "Coal City University",
  "Elizade University",
  "Evangel University, Akaeze",
  "Godfrey Okoye University",
  "Hezekiah University",
  "Kings University",
  "Obong University",
  "Ritman University",
  "Summit University, Offa",
  "Tansian University",
  "Wigwe University",
  "Abia State University (ABSU)",
  "Adamawa State University (ADSU)",
  "Akwa Ibom State University (AKSU)",
  "Ambrose Alli University (AAU)",
  "Bauchi State University (BASUG)",
  "Bayelsa Medical University (BMU)",
  "Benue State University (BSUM)",
  "Borno State University (BOSU)",
  "Chukwuemeka Odumegwu Ojukwu University (COOU)",
  "Delta State University (DELSU)",
  "Ebonyi State University (EBSU)",
  "Edo State University Uzairue",
  "Ekiti State University (EKSU)",
  "Enugu State University of Science and Technology (ESUT)",
  "Gombe State University (GSU)",
  "Ibrahim Badamasi Babangida University (IBBU)",
  "Ignatius Ajuru University of Education (IAUE)",
  "Imo State University (IMSU)",
  "Kaduna State University (KASU)",
  "Kano University of Science and Technology (KUST)",
  "Katsina State University (UMYU)",
  "Kebbi State University of Science and Technology (KSUSTA)",
  "Kogi State University (KSU)",
  "Kwara State University (KWASU)",
  "Ladoke Akintola University of Technology (LAUTECH)",
  "Lagos State University of Science and Technology (LASUSTECH)",
  "Lagos State University of Education (LASUED)",
  "Nasarawa State University (NSUK)",
  "Niger Delta University (NDU)",
  "Olabisi Onabanjo University (OOU)",
  "Ondo State University of Science and Technology (OSUSTECH)",
  "Osun State University (UNIOSUN)",
  "Plateau State University (PLASU)",
  "Rivers State University (RSU)",
  "Sokoto State University (SSU)",
  "Tai Solarin University of Education (TASUED)",
  "Taraba State University (TSU)",
  "Yobe State University (YSU)",
  "Zamfara State University (ZAMSU)",
];

export const MISSIONS = [
  {
    id: "m1",
    title: "Build a Simple Webpage",
    description: "Create a basic HTML/CSS page about your favorite Nigerian landmark.",
    points: 50,
    category: "Tech",
  },
  {
    id: "m2",
    title: "Write a Business Plan",
    description: "Draft a 1-page business plan for a local startup idea.",
    points: 100,
    category: "Business",
  },
  {
    id: "m3",
    title: "Health Awareness Campaign",
    description: "Create a social media post explaining the importance of clean water.",
    points: 75,
    category: "Medicine",
  },
  {
    id: "m4",
    title: "Solve 10 Math Problems",
    description: "Complete the weekly calculus challenge on the Study Helper.",
    points: 40,
    category: "General",
  },
];

export const OPPORTUNITIES = [
  {
    id: "o1",
    title: "Frontend Intern",
    company: "Paystack",
    location: "Lagos / Remote",
    type: "Internship",
  },
  {
    id: "o2",
    title: "Business Analyst Trainee",
    company: "Kuda Bank",
    location: "Lagos",
    type: "Trainee",
  },
  {
    id: "o3",
    title: "Medical Research Assistant",
    company: "NCDC",
    location: "Abuja",
    type: "Mentorship",
  },
  {
    id: "o4",
    title: "Product Design Mentee",
    company: "Flutterwave",
    location: "Remote",
    type: "Mentorship",
  },
];

export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "yo", name: "Yoruba (Mock)" },
  { code: "ha", name: "Hausa (Mock)" },
  { code: "ig", name: "Igbo (Mock)" },
  { code: "fr", name: "French (Mock)" },
  { code: "ar", name: "Arabic (Mock)" },
  { code: "pt", name: "Portuguese (Mock)" },
];
